import pandas as pd

pb_tags = pd.DataFrame(
    {
        'tag': [
            'CC',
            'CD',
            'DT',
            'EX',
            'IN',
            'JJ',
            'JJR',
            'JJS',
            'LS',
            'MD',
            'NN',
            'NNP',
            'NNS',
            'PDT',
            'POS',
            'PRP',
            'PRP$',
            'RB',
            'RBR',
            'RBS',
            'RP',
            'TO',
            'UH',
            'VB',
            'VBD',
            'VBG',
            'VBN',
            'VBP',
            'VBZ',
            'WDT',
            'WP',
            'WRB'
        ],
        'description' : [
            'conjunction, coordinating',
            'numeral, cardinal',
            'determiner',
            'existential there',
            'preposition or conjunction, subordinating',
            'adjective or numeral, ordinal',
            'adjective, comparative',
            'adjective, superlative',
            'list item marker',
            'model auxiliary',
            'noun, common, singular or mass',
            'noun, proper, singular',
            'noun, common, plural',
            'pre-determiner',
            'genitive marker',
            'pronoun, personal',
            'pronoun, possessive',
            'adverb',
            'adverb, comparative',
            'adverb, superlative',
            'particle',
            '"to" as preposition or infinitive marker',
            'interjection',
            'verb, base form',
            'verb, past tense',
            'verb, present participle or gerund',
            'verb, past participle',
            'verb, present tense, not 3rd person singular',
            'verb, present tense, 3rd person singular',
            'WH-determiner',
            'WH-pronoun',
            'WH-adverb'
        ]
    }
)